<?php
$path = getenv("HTTP_SERVER_PATH");

	require_once $_SERVER["DOCUMENT_ROOT"].$path.'/database/db.php';

	function create_invoice($testID){
		global $path;
		date_default_timezone_set("America/Chicago");
		$test_list = NULL;
		$user = NULL;
		$layout = "";
		if(is_array($testID)){
			$test_list = $testID;
			$user = getUser($testID[0]);
		}else{
			$test_list = array($testID);
			$user = getUser($testID);
		}

		$layout .="Iowa State University".new_line(1);
		$layout .="Invoice For Use of Department Resources".new_line(2);

		$layout .="Generated By: Department of Construction, Civil and Environmental Engineering".new_line(2);

		$layout .= "Date Created".tab(1).": ".date("M d, Y").new_line(2);

		$layout .="Subject".tab(2).": Use of Department tools and equipment.".new_line(2);

		$layout .= "User".tab(2).": ".ucfirst($user['firstname'])." ".ucfirst($user['lastname']).new_line(1);
		$layout .= "University ID".tab(1).": ".$user['userID'].new_line(2);

		$layout .= "Department Account #: ".$user['accountNumber'].new_line(2);

		$totalSum = 0.0;

		foreach($test_list as $test){
			$invoiceData = create_invoice_data($test);
			foreach($invoiceData as $pname=>$project){
				$layout .= ">> Project Name: ".$pname.new_line(1);
				foreach($project as $tname=>$test){
					$layout .= tab(1).">> ".$tname.new_line(1);
					foreach($test as $cname=>$cart){
						$layout .= tab(2).">> ".$cname.new_line(1);
						$sum = 0.0;
						foreach($cart as $iname=>$instrument){
							$layout .= tab(3).">> ".sprintf("%-15s| Usage: %s %-8s @ $%-4s a %-8s = $%.2lf",$iname,$instrument['usage'],$instrument['units'],$instrument['cost'],$instrument['units'],(intval($instrument['cost'])*intval($instrument['usage'])))."".new_line(1);
							
							$sum += (intval($instrument['cost'])*intval($instrument['usage']));
						}
						$layout .= tab(3).">> CART TOTAL = ".sprintf("$%.2lf",$sum).new_line(1);
						$totalSum += $sum;
					}
				}
				$layout .= new_line(1);
			}
		}

		$layout .= ">> Total Cost = ".sprintf("$%.2lf",$totalSum).new_line(1);


		$invoice = fopen("invoices/".($user['username'].".".date("m.d.Y")).".txt", "w") or die("Unable to open file!");
		fwrite($invoice,$layout);
		fclose($invoice);
	}

	function create_invoice_data($testID){
		$projectName = getData("name","project_list",array("projectID",getData("projectID","test_list",array("testID",$testID),$GLOBALS['testsdb'])[0]['projectID']),$GLOBALS['projectsdb'])[0]['name'];
		$testName 	 = getData("name","test_list", array("testID",$testID), $GLOBALS['testsdb'])[0]['name'];
		$carts		 = getData(array("cartID",'name'),"cart_list",array("testID",$testID),$GLOBALS['cartsdb']);

		$cartData    = array();

		foreach($carts as $cart){
			$what = array('instrumentID','usage_count','usage_time');
			$contents = getData($what,($GLOBALS['cartTablePrefix'].$cart['cartID']),"",$GLOBALS['cartsdb']);
				
			$newCart = array();
			for($i = 0; $i < count($contents); $i++){
				$where = array("instrumentID",$contents[$i]['instrumentID']);
				$what = array("type","cost");
				$addition = getData($what,"instruments",$where,$GLOBALS['instrumentsdb'])[0];

				$contents[$i] = array_merge($contents[$i],$addition);
				$usage = $unit = NULL;
				if($contents[$i]['type'] == 0){
					unset($contents[$i]['usage_time']);
					$usage = $contents[$i]['usage_count'];
					unset($contents[$i]['usage_count']);
					$unit = "units";
				}
				else{ 
					unset($contents[$i]['usage_count']);
					$usage = $contents[$i]['usage_time'];
					unset($contents[$i]['usage_time']);
					$unit = "minutes";
				}

				$usage = array('usage'=>$usage);
				$unit = array('units'=>$unit);

				$contents[$i] = array_merge($contents[$i],$usage);
				$contents[$i] = array_merge($contents[$i],$unit);

				$named_inst = array(getInstrument($contents[$i]['instrumentID'])['name']=>$contents[$i]);
				$newCart = array_merge($newCart, $named_inst);
			}

			$cartData = array_merge($cartData,array($cart['name']=>$newCart));
		}

		$fileContents = array(
			$projectName=>array(
				$testName=>$cartData
			)
		);

		return $fileContents;
	}


	function new_line($time){
		$space = "";
		for($i = 0; $i < $time; $i++){
			$space .= "\r\n";
		}
		return $space;
	}

	function space($time){
		$space = "";
		for($i = 0; $i < $time; $i++){
			$space .= " ";
		}
		return $space;
	}

	function tab($time){
		$space = "";
		for($i = 0; $i < $time; $i++){
			$space .= "	";
		}
		return $space;
	}

?>

